In [3]:
import numpy as np

# Numpy 配列の生成
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [7]:
# Numpy の算術計算
x = np.array([1.0, 2.0, 3.0])
y = np.array([4.0, 5.0, 6.0])
# 要素ごとに計算
print(x + y)
print(x - y)
print(x * y)
print(x / y)


[5. 7. 9.]
[-3. -3. -3.]
[ 4. 10. 18.]
[0.25 0.4  0.5 ]


In [8]:
# ブロードキャスト
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

In [12]:
# Numpy の　N次配列
# 行列
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape) # 行列Aの形状
print(A.dtype) # Aの要素のデータ型


[[1 2]
 [3 4]]
(2, 2)
int64


In [14]:
# 行列の算術計算
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 0], [0, 6]])
print(A + B)
print(A * B)
print(A * 10) # スカラ値でブロードキャスト

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]
[[10 20]
 [30 40]]


In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B # ベクトルでブロードキャスト

array([[10, 40],
       [30, 80]])

In [18]:
# 要素のへのアクセス
X = np.array([[51, 55], [23, 57], [46, 98]])
print(X)
print(X[0])
print(X[0][1])

for row in X: # for文を使って各要素にアクセス
    print(row)

[[51 55]
 [23 57]
 [46 98]]
[51 55]
55
[51 55]
[23 57]
[46 98]


In [22]:
X = np.array([[51, 55], [23, 57], [46, 98]])
X = X.flatten() # Xをベクトルに変換
print(X)
print(X[np.array([0, 2, 4])]) # インデックスが0, 2, 4番目の要素を取得
print(X > 50)
print(X[X > 50]) # 50以上の要素を取得

[51 55 23 57 46 98]
[51 23 46]
[ True  True False  True False  True]
[51 55 57 98]
